version: '3.8'

services:
  user-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=mySecret
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=usersdb
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"